In [47]:
import numpy as np
import qai_hub as hub
from qai_hub_models.models.mediapipe_face import Model
import torch
import cv2

import sys
sys.path.append('./')
from helper import random_color_images_batch, process_image_for_model

In [48]:
images = random_color_images_batch(batch_size=8, csv_path="file_paths.csv")
images_processed = process_image_for_model(images)

In [49]:
images[0]

array([[[160, 189, 216],
        [189, 213, 235],
        [203, 221, 232],
        ...,
        [162, 159, 175],
        [168, 160, 177],
        [165, 157, 174]],

       [[171, 201, 226],
        [198, 223, 243],
        [207, 226, 234],
        ...,
        [161, 158, 174],
        [165, 159, 176],
        [165, 157, 174]],

       [[161, 192, 215],
        [193, 219, 236],
        [206, 225, 232],
        ...,
        [160, 157, 173],
        [164, 158, 175],
        [163, 157, 174]],

       ...,

       [[126, 138, 138],
        [123, 135, 135],
        [124, 136, 136],
        ...,
        [133, 137, 155],
        [131, 137, 150],
        [128, 134, 145]],

       [[124, 135, 133],
        [123, 134, 132],
        [125, 136, 134],
        ...,
        [137, 136, 156],
        [135, 135, 151],
        [130, 133, 147]],

       [[126, 137, 135],
        [126, 137, 135],
        [129, 137, 136],
        ...,
        [138, 136, 156],
        [134, 134, 150],
        [131, 132, 146]]

In [50]:
if torch.is_tensor(images):
    images = images.numpy()

In [51]:
images[0]

array([[[160, 189, 216],
        [189, 213, 235],
        [203, 221, 232],
        ...,
        [162, 159, 175],
        [168, 160, 177],
        [165, 157, 174]],

       [[171, 201, 226],
        [198, 223, 243],
        [207, 226, 234],
        ...,
        [161, 158, 174],
        [165, 159, 176],
        [165, 157, 174]],

       [[161, 192, 215],
        [193, 219, 236],
        [206, 225, 232],
        ...,
        [160, 157, 173],
        [164, 158, 175],
        [163, 157, 174]],

       ...,

       [[126, 138, 138],
        [123, 135, 135],
        [124, 136, 136],
        ...,
        [133, 137, 155],
        [131, 137, 150],
        [128, 134, 145]],

       [[124, 135, 133],
        [123, 134, 132],
        [125, 136, 134],
        ...,
        [137, 136, 156],
        [135, 135, 151],
        [130, 133, 147]],

       [[126, 137, 135],
        [126, 137, 135],
        [129, 137, 136],
        ...,
        [138, 136, 156],
        [134, 134, 150],
        [131, 132, 146]]

In [52]:

torch.is_tensor(images_processed)

images_processed[0].shape

torch.Size([3, 192, 192])

In [53]:
# Load the model
torch_model = Model.from_pretrained()

# Device
device = hub.Device("CPU")
results = torch_model.face_landmark_detector(images_processed)

# print(dir(torch_model))
print(results)
# Trace Model
# input_shape = torch_model.get_input_spec()
# sample_inputs = torch_model.sample_inputs()

# print(f"Input shape: {input_shape} \n Sample Inputs: {sample_inputs}")

(tensor([0.0001, 0.0003, 0.0001, 0.0108, 0.0018, 0.0002, 0.0006, 0.0002]), tensor([[[ 0.4501,  0.6709, -0.0351],
         [ 0.4645,  0.6005, -0.1170],
         [ 0.4547,  0.6193, -0.0541],
         ...,
         [ 0.4951,  0.4388, -0.0321],
         [ 0.6231,  0.4167,  0.0254],
         [ 0.6363,  0.4010,  0.0269]],

        [[ 0.4701,  0.6759, -0.0403],
         [ 0.4574,  0.6011, -0.1113],
         [ 0.4688,  0.6228, -0.0541],
         ...,
         [ 0.5027,  0.4469, -0.0330],
         [ 0.6409,  0.4209, -0.0102],
         [ 0.6541,  0.4040, -0.0116]],

        [[ 0.4997,  0.7153, -0.0264],
         [ 0.4716,  0.6449, -0.1087],
         [ 0.4943,  0.6603, -0.0461],
         ...,
         [ 0.5298,  0.4717, -0.0565],
         [ 0.6804,  0.4360, -0.0545],
         [ 0.6948,  0.4164, -0.0585]],

        ...,

        [[ 0.5252,  0.6642, -0.0279],
         [ 0.5331,  0.5944, -0.1004],
         [ 0.5326,  0.6119, -0.0444],
         ...,
         [ 0.5871,  0.4384, -0.0395],
         [ 0.

In [54]:
import cv2
def draw_landmarks(img, points, connections=[], color=(0, 255, 0), size=2):
    h, w = img.shape[:2]
    points = points.copy()
    for point in points:
        x, y = point[:2]
        if 0 <= x <= 1 and 0 <= y <= 1:
            x = int(x * w)
            y = int(y * h)
            cv2.circle(img, (x, y), size, color, thickness=size)
    # Draw connections if needed
    return img

In [55]:
points = results[1][0]
img    = images[0]



In [56]:
img.shape

(480, 640, 3)

In [57]:
if torch.is_tensor(points):
    points = points.numpy()

In [58]:
output = draw_landmarks(img, points)
cv2.imwrite("facial_detection.png", output)

True